using System;
using System.Collections.Generic;

namespace SmartBoard.Data.Models.SmartBoard
{
    public partial class VistaObra
    {
        public string Obras { get; set; }
        public int Id { get; set; }
        public int? Idpoadetalle { get; set; }
        public int? Year { get; set; }
        public string Region { get; set; }
        public int? Idmunicipio { get; set; }
        public int? Idlocalidad { get; set; }
        public int? Iddependencia { get; set; }
        public int? Idestadoobra { get; set; }
        public int? Idestadorevision { get; set; }
        public int? Idprogsog { get; set; }
        public int? Idvertiente { get; set; }
        public int? Idsubvertiente { get; set; }
        public int? Idcategoria { get; set; }
        public int? Idunidadmedida { get; set; }
        public int? Idejecutor { get; set; }
        public int? Ideje { get; set; }
        public int? Numeroobra { get; set; }
        public string Nombreobra { get; set; }
        public string Descripcion { get; set; }
        public decimal? Inversion { get; set; }
        public string Fuentefinanciamiento { get; set; }
        public string Coordenadax { get; set; }
        public string Coordenaday { get; set; }
        public bool Inaguracion { get; set; }
        public int? PeriodoInforme { get; set; }
        public decimal? Porcentajeavance { get; set; }
        public DateTime? Fechainicio { get; set; }
        public DateTime? Fechatermino { get; set; }
        public bool Posibleconflicto { get; set; }
        public string Observaciones { get; set; }
        public bool Georeferenciado { get; set; }
        public int? NumeroreferenciaCiceco { get; set; }
        public string Imagenobra { get; set; }
        public string Observacionesrevision { get; set; }
        public DateTime? Fecharegistro { get; set; }
        public string BeneficiarioNombre { get; set; }
        public string BeneficiarioDomicilio { get; set; }
        public string Numeroobraexterno { get; set; }
        public decimal? InversionFederal { get; set; }
        public decimal? InversionEstatal { get; set; }
        public decimal? InversionMunicipal { get; set; }
        public decimal? InversionBeneficiario { get; set; }
        public int? CantidadBeneficioHombre { get; set; }
        public int? CantidadBeneficioMujer { get; set; }
        public int? CantidadUnidadmedida { get; set; }
        public string Expediente { get; set; }
        public decimal? AvanceFinanciero { get; set; }
        public string Municipios { get; set; }
        public int? Expr1 { get; set; }
        public int? Idregion { get; set; }
        public int? Idtipomunicipio { get; set; }
        public int? Idgdo { get; set; }
        public int? IddistritoLocal { get; set; }
        public int? IddistrictoFederal { get; set; }
        public string Expr2 { get; set; }
        public string Municipio { get; set; }
        public decimal? Expr3 { get; set; }
        public int? Sduop { get; set; }
        public int? Capaseg { get; set; }
        public int? Cicaeg { get; set; }
        public int? Igife { get; set; }
        public int? TotalObras { get; set; }
        public string Clave { get; set; }
        public string Partido { get; set; }
        public int? Idzona { get; set; }
        public int? Delega { get; set; }
        public string Presidente { get; set; }
        public int? PobTot { get; set; }
        public int? Indice { get; set; }
        public int? Pobhom { get; set; }
        public int? Pobmun { get; set; }
        public int? Listan { get; set; }
        public int? Munis { get; set; }
        public int? Secciones { get; set; }
        public int? Casillas { get; set; }
        public int? Totviv { get; set; }
        public int? Sindrenaje { get; set; }
        public int? Posine { get; set; }
        public int? Pobtotiind { get; set; }
        public int? Cobagua { get; set; }
        public int? Cobelect { get; set; }
        public int? Cobdren { get; set; }
        public int? Totpiso { get; set; }
        public int? Lugest { get; set; }
        public int? Lugnal { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Gdeshum { get; set; }
        public string Localidades { get; set; }
        public int? Expr4 { get; set; }
        public int? Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Nombre { get; set; }
        public double? Pobtot95 { get; set; }
        public double? Indice95 { get; set; }
        public string Grado95 { get; set; }
        public DateTime? Expr7 { get; set; }
        public bool? Activo { get; set; }
        public string Expr8 { get; set; }
        public string Vertiente { get; set; }
        public int? Expr9 { get; set; }
        public string Expr10 { get; set; }
        public bool? Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string SubVertiente { get; set; }
        public int? Expr13 { get; set; }
        public string Expr14 { get; set; }
        public string Expr15 { get; set; }
        public bool? Expr16 { get; set; }
        public int? Expr17 { get; set; }
        public string Categoria { get; set; }
        public int? Expr18 { get; set; }
        public string Expr19 { get; set; }
        public string Expr20 { get; set; }
        public bool? Expr21 { get; set; }
        public string Unidadmedida { get; set; }
        public int? Expr22 { get; set; }
        public string Expr23 { get; set; }
        public bool? Expr24 { get; set; }
        public string Ejecutor { get; set; }
        public int? Expr25 { get; set; }
        public string Expr26 { get; set; }
        public bool? Expr27 { get; set; }
    }
}
